version: "3"
services: 
    redis:
        image: redis
        ports:
            - 6379:6379
        volumes:
            - "redis:/data"
    web:
        image: fitzaudoen/flaskcointracker
        env_file: production.env
        command: gunicorn flaskcointracker:app -b :5000
        depends_on: 
            - redis
            - db
        ports:
            - 5000:5000
    
    worker:
        image: fitzaudoen/flaskcointracker
        env_file: production.env
        command: celery worker -A flaskcointracker.celery
        depends_on: 
            - "redis"

    worker2:
        image: fitzaudoen/flaskcointracker
        env_file: production.env
        command: celery beat -A flaskcointracker.celery
        depends_on: 
            - "redis"

    db:
        image: postgres:12-alpine
        env_file: postgres.env
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        
   
volumes:
    redis: {}
    postgres_data:

