version: "3"
services: 
    redis:
        image: redis
        ports:
            - 6379:6379
        volumes:
            - "redis:/data"
    web:
        #image: fitzaudoen/flaskcointracker
        build:
            context: "."
        command: gunicorn flaskcointracker:app -b :5000
        depends_on: 
            - redis
            - db
        ports:
            - 5000:5000
    
    worker:
        build: 
            context: "."
        command: celery worker -A flaskcointracker.celery
        depends_on: 
            - "redis"

    worker2:
        build: 
            context: "."
        command: celery beat -A flaskcointracker.celery
        depends_on: 
            - "redis"

    db:
        image: postgres:12-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
        - POSTGRES_USER=cointrackerdb
        - POSTGRES_PASSWORD=cointrackerdb
        - POSTGRES_DB=cointrackerdb_prod
volumes:
    redis: {}
    postgres_data:

