"""empty message

Revision ID: 81c5bf0cd27b
Revises: 7bc9cdd1a9aa
Create Date: 2020-07-16 12:25:09.768720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c5bf0cd27b'
down_revision = '7bc9cdd1a9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coin', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('initial_price', sa.Float(), nullable=True))
        batch_op.drop_column('direction')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('initial_price')
        batch_op.drop_column('coin')

    # ### end Alembic commands ###
